import { mkdir, readFile, writeFile } from "node:fs/promises";
const script = await readFile(new URL("./install.sh", import.meta.url), "utf8");
await mkdir(new URL("./dist/", import.meta.url), { recursive: true });
await writeFile(
  new URL("./dist/worker.mjs", import.meta.url),
  `// Generated by build.mjs from install.sh; do not edit.\nconst script = ${JSON.stringify(script)};\nexport default { fetch() { return new Response(script, { headers: { 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff' } }); } };\n`,
);
